# Site settings
title: "Bliss Title" #the title of the site: maybe your name?
url: "https://writerthethinker1.github.io/" #use the format username.github.io
baseurl: "/bliss_work/" #the repo name on your github account...
author: "writerthinker" #put your name here...

mathjax: true #if you want to use math...
markdown: kramdown
highlighter: rouge
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink: pretty

# parts you edit!
# the phrases for the site...customize to your liking, all after the '>'
bliss_phrase: >

  Add own vocational phrase...

talks_summary: >

  Basically about field of food quality control and some software engineering. Had some great ideas and new developments!

project_desc: >

  Company and personal coding projects as well as new ideas!

works_description: >

  Just some papers and other things related to the field, some during work and others just for fun!

paginate: 10 #the number of talks you want per page
paginate_path: '/:num'

other_files_link: "professional_files/others/"

#####

# collections, static files, and plugin information...don't edit!!

collections:
  projects:
    output: true

defaults:
  - scope:
      path: "professional_files/articles"
    values:
      articles: true
  - scope:
      path: "professional_files/books"
    values:
      books: true
  - scope:
      path: "professional_files/extras"
    values:
      extras: true
  - scope:
      path: "professional_files/papers"
    values:
      papers: true


plugins:
  - jekyll-paginate
