# Site settings
title: "Vocational Bliss"
url: "https://writerthethinker1.github.io/"
baseurl: "/bliss_work/"

markdown: kramdown
highlighter: rouge
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
bliss_phrase: >

  add own vocational phrase...

work_summary: >

  add summary of posts: what are they about?



# Utils
mathjax: false
