# Site settings
title: "Professional Blog"
url: "https://writerthethinker1.github.io/"
baseurl: "/bliss_work/"

markdown: kramdown
highlighter: rouge
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty

# Utils
mathjax: false
