# Site settings
title: "Bliss Title"
url: "https://writerthethinker1.github.io/"
baseurl: "/bliss_work/"

markdown: kramdown
highlighter: rouge
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
bliss_phrase: >

  Add own vocational phrase...

work_summary: >

  Basically about field of food quality control and some software engineering. Had some great ideas and new developments!

project_desc: >

  Company and personal coding projects as well as new ideas!

paginate: 10
paginate_path: '/:num'

collections:
  projects:
    output: true

# Utils
mathjax: false

plugins:
  - jekyll-paginate
